import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import fs from "fs";
import path from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const buildDir = "build";

// Clean build directory
if (fs.existsSync(buildDir)) {
  fs.rmSync(buildDir, { recursive: true, force: true });
}
fs.mkdirSync(buildDir, { recursive: true });

// Copy manifest and versions files
fs.copyFileSync("manifest.json", path.join(buildDir, "manifest.json"));
fs.copyFileSync("versions.json", path.join(buildDir, "versions.json"));

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: path.join(buildDir, "main.js"),
});

if (prod) {
  await context.rebuild();
  console.log("Build complete! Files are in the 'build' directory.");
  console.log(
    "Copy the entire 'build' folder to your Obsidian vault's .obsidian/plugins/ directory.",
  );
  process.exit(0);
} else {
  console.log("Watching for changes...");
  await context.watch();
}
